name: Deploy to Hostinger

on:
  push:
    branches:
      - main # Ocorre o deploy quando houver push na branch 'main'

jobs:
  web-deploy:
    name: 🎉 Deploy to Hostinger
    runs-on: ubuntu-latest

    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: 📂 Sync files (Deploy)
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: ${{ secrets.FTP_SERVER_DIR }} # Define a pasta no Hostinger pelas Secrets
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          .env*
          README.md
          **/.vscode/**
          .github/**
